### ISSUE TITLE
ltop needs to show recovery window for MDT

### ISSUE THREAD

**Issue by morrone** [LLNL/lmt#2]
ltop needs to display (and lmt needs to report through cerebro) the same kind of recovery info that the OSTs display.

**Comment by ofaaland** [comment]
Submitted a pull request for feedback: https://github.com/chaos/lmt/pull/27

**Comment by ofaaland** [comment]
Addressed by https://github.com/LLNL/lmt/commit/e3cba331b179c821a67098f2c099159f951ab6ad
