### ISSUE TITLE
lustre 2.12 support

### ISSUE THREAD

**Issue by jaemin-joo** [LLNL/lmt#35]
I have trouble to execute "lmtmetric -m ost/mdt" in lustre 2.12 environment. 

$ lmtmetric -m ost
lmtmetric: error reading lustre failover-OST0000 uuid from proc: No such file or directory
lmtmetric: ost metric: No such file or director

When I look at below issue, it might be similar cases. but I want to make sure this issue is caused by lustre version (2.12)

**Comment by ofaaland** [comment]
Yes, this is because lmt needs updates to support Lustre 2.12.  The "uuid" file moved from /proc/fs/lustre/obdfilter/*/uuid to /sys/fs/lustre/obdfilter/*/uuid.

**Comment by ofaaland** [comment]
@jaemin-joo I've started work on a patch at

https://github.com/ofaaland/lmt/tree/b-lustre-212

which might make lmt work with Lustre 2.12.  It passes several tests, but hasn't been through full testing yet.  So I cannot guarantee it will work, but it's there if you want to try it.

**Comment by ofaaland** [comment]
@jaemin-joo I performed more testing and I believe the patch is good.  See Pull Request #36
