### ISSUE TITLE
lmt_mysql: failed to connect to database

### ISSUE THREAD

**Issue by jaemin-joo** [LLNL/lmt#37]
I installed lmt-3.2.6 rpms to solve the lustre 2.12 problem as your guide. It's solved that I ask you in lustre 2.12. but I got the other issue like below command. 
When I start cerebrod process, lmt_mysql module doesn't connect to database of local mysql.
I am done installation of mysql which has database schema. 
let me know how to configure to solve this.

$ systemctl restart cerebrod
$ tailf /var/log/messages
May 20 21:19:46 ansible1 cerebrod: Starting cerebrod: [  OK  ]
May 20 21:19:46 ansible1 systemd: Started LSB: cerebrod startup script.
May 20 21:19:47 ansible1 /usr/sbin/cerebrod[17870]: lmt_mysql: failed to connect to database

**Comment by jaemin-joo** [comment]
I find that the problem is related to mariadb password. after removing mariadb password, the error message is not came out.

**Comment by alvaromartin990** [comment]
@jmjoo I am experiencing the same issue.

What do you mean with removing mariadb password? Removing it from the lmt.conf file or removing /etc/lmt/rwpasswd?
