### ISSUE TITLE
lmt-server configure failure with cerebro-0.9.2-1

### ISSUE THREAD

**Issue by louiscaocao** [LLNL/lmt#55]
As the below log shows, I have installed cerebro-0.9.2. The checking for cerebro.h failure while configure. 

checking for mysql_config... /opt/rh/rh-mysql57/root/usr/bin/mysql_config
checking cerebro.h usability... no
checking cerebro.h presence... no
checking for cerebro.h... no
configure: error: Please install cerebro or configure --disable-cerebro
[root@node03 lmt-3.2.10]# which cerebro
/usr/bin/cerebro
cerebro-0.9.2-1.noarch
[root@node03 lmt-3.2.10]#

**Comment by ofaaland** [comment]
@louiscaocao what version of autoconf does your node have?  And what operating system and version is it running?  Thanks

**Comment by ofaaland** [comment]
@louiscaocao also, where is cerebro.h?  On an rpm-based system, you can find out like this:
```
$ rpm -ql cerebro | grep 'cerebro\.h'
/usr/include/cerebro.h
```

thanks

**Comment by ofaaland** [comment]
Actually, @louiscaocao  I believe you have the wrong cerebro.  Nevermind my previous questions about autoconf and the location of cerebro.h. 

Your package information should be similar to this:
```
[ofaaland@fubar tmp]$ rpm -qi cerebro
Name        : cerebro
...
Summary     : Cerebro cluster monitoring tools and libraries
Description :
Cerebro is a collection of cluster monitoring tools and libraries.

```
which you can get from https://github.com/chaos/cerebro or it may be packaged by your OS vendor.

I think you have something more like this:
```
[ofaaland@fubar wrong-cerebro]$ rpm -qi --package cerebro-0.9.2-1.noarch.rpm
Name        : cerebro
Version     : 0.9.2
Release     : 1
Architecture: noarch
...
URL         : http://github.com/lmenezes/cerebro
Summary     : Elasticsearch web admin tool
Description :
cerebro is an open source(MIT License) elasticsearch web admin tool built
  using Scala, Play Framework, AngularJS and Bootstrap.
```
These are unrelated packages that happen to have the same name.  LMT works with the cluster monitoring tool.

**Comment by louiscaocao** [comment]
Thank you. You are right I get a wrong cerebro.
