### ISSUE TITLE
ltop: Prioritize display of MDTs when focus on MDT window

### ISSUE THREAD

**Issue by cmharr** [LLNL/lmt#63]
Currently, with large numbers of OSTs and MDTs, the display of OSTs is prioritized in `ltop`. When pressing `z` to switch focus to the MDT window, the display of  the MDTs should receive priority, with OSTs showing in available remaining space in the terminal. Similarly, when the OST window has the focus, display of OSTs should take priority.

This will help installations with many MDTs and OSTs where a terminal can't show all targets.

**Comment by defaziogiancarlo** [comment]
This issue addressed by the commit a17d49f8d6b989a30aac336e4c287bfced1e77ea
which creates a new layout that prioritizes either OSTs (default) or MDTs.

**Comment by ofaaland** [comment]
@defaziogiancarlo did you tag a new LMT release and push the tag to github?  If so, you can close this issue as resolved.
