### ISSUE TITLE
Missing configuration file or configuration info: /etc/lmt/lmt.conf

### ISSUE THREAD

**Issue by alvaromartin990** [LLNL/lmt#67]
Get MySQL or MariaDB Working Configuration.

My lustre file system name is temp. Following the steps on the configuration documentation:
`/usr/sbin/lmtinit -a temp`
```
/usr/sbin/lmtinit -l
temp
```
```
sudo /sbin/service cerebrod restart
Restarting cerebrod (via systemctl):                       [  OK  ]
```
```
/usr/sbin/lmtsh -f temp
[LMT:init] Missing configuration file or configuration info: /etc/lmt/lmt.conf
```

However, my lmt.conf file is at /etc/lmt and looks like;
```
    lmt_db_host = nil
    lmt_db_port = 0
    lmt_db_rouser = "lwatchclient"
    lmt_db_ropasswd = "mypass"
    lmt_db_rwuser = "lwatchadmin"
    lmt_db_rwpasswd = "mypass"
```

I have try multiple approaches such as getting rid of MySQL and install it again, delete all dbs on the system, different lmt.conf parameters. 

What could I do to fix this?

**Comment by alvaromartin990** [comment]
sudo systemctl status cerebrod -l
● cerebrod.service - LSB: cerebrod startup script
   Loaded: loaded (/etc/rc.d/init.d/cerebrod; bad; vendor preset: disabled)
   Active: active (running) since Tue 2024-10-29 00:20:16 UTC; 9min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 13945 ExecStop=/etc/rc.d/init.d/cerebrod stop (code=exited, status=0/SUCCESS)
  Process: 13961 ExecStart=/etc/rc.d/init.d/cerebrod start (code=exited, status=0/SUCCESS)
    Tasks: 6
   CGroup: /system.slice/cerebrod.service
           └─13970 /usr/sbin/cerebrod

Oct 29 00:27:50 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:28:05 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:28:20 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:28:35 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:28:50 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:29:05 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:29:20 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:29:35 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:29:50 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database
Oct 29 00:30:05 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[13970]: lmt_mysql: failed to connect to database

**Comment by ofaaland** [comment]
Hi @alvaromartin990 I believe https://github.com/LLNL/lmt/pull/68 will fix your `Missing configuration file or configuration info: /etc/lmt/lmt.conf` error.  Are you able to build with that patch and let me know?

**Comment by alvaromartin990** [comment]
@ofaaland , thank you so much for your help. 

I was able to add the patch, build the new rpm, and install the lmt-server on my management node. Unfortunately, I still find the same error. I am currently running cerebro 1.18-1 (found at Sourceforge):
```

● cerebrod.service - LSB: cerebrod startup script
   Loaded: loaded (/etc/rc.d/init.d/cerebrod; bad; vendor preset: disabled)
   Active: active (running) since Wed 2024-10-30 16:13:01 UTC; 58s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 140685 ExecStart=/etc/rc.d/init.d/cerebrod start (code=exited, status=0/SUCCESS)
    Tasks: 6
   CGroup: /system.slice/cerebrod.service
           └─140700 /usr/sbin/cerebrod

Oct 30 16:13:01 lustre-mount-client-dev-renewed.novalocal systemd[1]: Starting LSB: cerebrod startup script...
Oct 30 16:13:01 lustre-mount-client-dev-renewed.novalocal cerebrod[140685]: Starting cerebrod: [  OK  ]
Oct 30 16:13:01 lustre-mount-client-dev-renewed.novalocal systemd[1]: Started LSB: cerebrod startup script.
Oct 30 16:13:05 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[140700]: lmt_mysql: failed to connect to database
```
and the error:
```
sudo /usr/sbin/lmtinit -a temp
sudo /usr/sbin/lmtinit -l
temp
sudo /sbin/service cerebrod restart
Restarting cerebrod (via systemctl):                       [  OK  ]
sudo /usr/sbin/lmtsh -f temp
[LMT:init] Missing configuration file or configuration info: /etc/lmt/lmt.conf
```

I am still pretty new to lustre, so I might be doing something wrong. 
Thank you!

**Comment by ofaaland** [comment]
Hi @alvaromartin990 what is the output of these commands now that you've updated your install?
```
grep lmtinit /usr/share/lmt/LMT.pm
grep -A3 BEGIN /usr/sbin/lmtsh
cat /etc/lmt/lmt.conf
sudo /usr/sbin/lmtinit lmtinit -c /etc/lmt/lmt.conf -x
```

> I am still pretty new to lustre, so I might be doing something wrong.
Not to worry.  So far you've identified real bugs, so thank you!

**Comment by alvaromartin990** [comment]
@ofaaland , thank you for your answer. Here are the outputs:
```
grep -A3 BEGIN /usr/sbin/lmtsh
BEGIN {
    $ENV{PERL_READLINE_NOWARN} = 1;
    push @INC, "/usr/share/lmt";
}
```
```
grep lmtinit /usr/share/lmt/LMT.pm
    if (open HELPER, "/usr/sbin/lmtinit -x -c $file|") {
```
```
cat /etc/lmt/lmt.conf
--
-- Example lmt.conf
-- Note: this file is parsed by an embedded LUA interpreter
--

lmt_cbr_debug = 0

lmt_proto_debug = 0

lmt_db_debug = 0

lmt_db_autoconf = 1

lmt_db_host = nil
lmt_db_port = 0

lmt_db_rouser = "lwatchclient"
lmt_db_ropasswd = "alvaroWM1*"
lmt_db_rwuser = "lwatchadmin"
lmt_db_rwpasswd = "alvaroWM1*"

--
-- Assign lmt_db_rwpasswd from contents of rwpasswd file,
-- or if not readable, assign a nil password.  Using this strategy,
-- only UNIX users able to read the file can authenticate for read-write.
--

f = io.open("/etc/lmt/rwpasswd")
if (f) then
  lmt_db_rwpasswd = f:read("*l")
  f:close()
else
  lmt_db_rwpasswd = nil
end

```
```
sudo /usr/sbin/lmtinit lmtinit -x -c /etc/lmt/lmt.conf
Usage: lmtinit [OPTIONS]
  -a,--add FS            create database for file system
  -d,--delete FS         remove database for file system
  -l,--list              list configured file systems
  -c,--config-file FILE  use an alternate config file
  -s,--schema-file FILE  use an alternate schema file
  -u,--user=USER         connect to the db with USER
  -p,--password=PASS     connect to the db with PASS
  -P,--prompt-password   prompt for password
  -x,--dump-config       dump config in machine readable form
  -o,--update-ops FS     update the mdt op names for file system
```
Thank you for your help!

**Comment by ofaaland** [comment]
Thanks @alvaromartin990 .  I had a typo in that last command, an extra "lmtinit" as the first argument that shouldn't be there.  Please run `sudo /usr/sbin/lmtinit -x -c /etc/lmt/lmt.conf` and provide the output, thanks!

**Comment by alvaromartin990** [comment]
@ofaaland , same output:

```
sudo /usr/sbin/lmtinit -x -c /etc/lmt/lmt.conf 
Usage: lmtinit [OPTIONS]
  -a,--add FS            create database for file system
  -d,--delete FS         remove database for file system
  -l,--list              list configured file systems
  -c,--config-file FILE  use an alternate config file
  -s,--schema-file FILE  use an alternate schema file
  -u,--user=USER         connect to the db with USER
  -p,--password=PASS     connect to the db with PASS
  -P,--prompt-password   prompt for password
  -x,--dump-config       dump config in machine readable form
  -o,--update-ops FS     update the mdt op names for file system
```

**Comment by ofaaland** [comment]
@alvaromartin990 thanks!  What do you get for this:
```
strings /usr/sbin/lmtinit | grep ERROR
```

**Comment by alvaromartin990** [comment]
@ofaaland, thanks! I am not getting any output for that one. Also tried with sudo.

**Comment by ofaaland** [comment]
> I am not getting any output for that one. Also tried with sudo.

I believe that means your installed `lmtinit` is not built with my patch.  This is what you should see:

```
$strings utils/lmtinit |grep ERROR 
ERROR: unexpected arguments, have %d expected %d
ERROR: one of these must be enabled: -a -d -l -x -o (%d,%d,%d,%d,%d)
MARIADB_CONNECTION_ERROR_ID
MARIADB_CONNECTION_ERROR
MARIADB_CLIENT_ERRORS
```

Note the two lines that begin with "ERROR:" - these were added with the patch that fixed the arg parsing bug.

**Comment by alvaromartin990** [comment]
@ofaaland , thank you for your answer! I will double-check I re-installed everything correctly and get back to you.

**Comment by alvaromartin990** [comment]
hi @ofaaland , just built everything again. I think I did this successfully this time since I am getting something new I hadn't seen before:

```
sudo /usr/sbin/lmtsh -f temp
DBI connect('host=;port=0','lwatchadmin',...) failed: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory at /usr/share/lmt/LMT.pm line 292.
```
I also re-run everything again and included it here:
```
grep -A3 BEGIN /usr/sbin/lmtsh
BEGIN {
    $ENV{PERL_READLINE_NOWARN} = 1;
    push @INC, "/usr/share/lmt";
}
```
```
grep lmtinit /usr/share/lmt/LMT.pm
    if (open HELPER, "/usr/sbin/lmtinit -x -c $file|") {
```
```
cat /etc/lmt/lmt.conf
--
-- Example lmt.conf
-- Note: this file is parsed by an embedded LUA interpreter
--

lmt_cbr_debug = 0

lmt_proto_debug = 0

lmt_db_debug = 0

lmt_db_autoconf = 1

lmt_db_host = nil
lmt_db_port = 0

lmt_db_rouser = "lwatchclient"
lmt_db_ropasswd = "alvaroWM1*"

lmt_db_rwuser = "lwatchadmin"
lmt_db_rwpasswd = "alvaroWM1*"

--
-- Assign lmt_db_rwpasswd from contents of rwpasswd file,
-- or if not readable, assign a nil password.  Using this strategy,
-- only UNIX users able to read the file can authenticate for read-write.
--

f = io.open("/etc/lmt/rwpasswd")
if (f) then
  lmt_db_rwpasswd = f:read("*l")
  f:close()
else
  lmt_db_rwpasswd = nil
end
```
```
sudo cat /etc/lmt/rwpasswd
alvaroWM1*
```
This is the output this time!
```
sudo /usr/sbin/lmtinit -x -c /etc/lmt/lmt.conf 
dbhost:
dbport:0
dbuser:lwatchadmin
dbauth:alvaroWM1*
```
Also, if it helps, cerebrod still complains:
```
sudo service cerebrod status -l
● cerebrod.service - LSB: cerebrod startup script
   Loaded: loaded (/etc/rc.d/init.d/cerebrod; bad; vendor preset: disabled)
   Active: active (running) since Wed 2024-10-30 22:02:41 UTC; 2min 1s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 181861 ExecStop=/etc/rc.d/init.d/cerebrod stop (code=exited, status=0/SUCCESS)
  Process: 181878 ExecStart=/etc/rc.d/init.d/cerebrod start (code=exited, status=0/SUCCESS)
    Tasks: 6
   CGroup: /system.slice/cerebrod.service
           └─181887 /usr/sbin/cerebrod

Oct 30 22:02:41 lustre-mount-client-dev-renewed.novalocal systemd[1]: Started LSB: cerebrod startup script.
Oct 30 22:02:42 lustre-mount-client-dev-renewed.novalocal /usr/sbin/cerebrod[181887]: lmt_mysql: failed to connect to database
```
Thanks again!

**Comment by ofaaland** [comment]
Hi @alvaromartin990 please create a new issue for 

```
sudo /usr/sbin/lmtsh -f temp
DBI connect('host=;port=0','lwatchadmin',...) failed: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory at /usr/share/lmt/LMT.pm line 292.
```

This is distinct from the "Missing configuration file" issue.

In that new issue, paste in the contents of your "strings ... | grep " command from above - I think it's relevant.

thanks!
