### ISSUE TITLE
Authentication plugin 'caching_sha2_password' cannot be loaded

### ISSUE THREAD

**Issue by alvaromartin990** [LLNL/lmt#70]
Hi,

I am posting a new issue regarding _Authentication plugin 'caching_sha2_password' cannot be loaded_ error. This occurred while running the _lmtsh_ utility:

```
sudo /usr/sbin/lmtsh -f temp
DBI connect('host=;port=0','lwatchadmin',...) failed: Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory at /usr/share/lmt/LMT.pm line 292.
```
@ofaaland suggested that I include the following information:
```
strings /usr/sbin/lmtinit | grep ERROR
ERROR: unexpected arguments, have %d expected %d
ERROR: one of these must be enabled: -a -d -l -x -o (%d,%d,%d,%d,%d)
```
It is important to highlight that I built with [68](https://github.com/LLNL/lmt/pull/68) patch, following @ofaaland 's instructions. 

I also tried [changing the encryption of the passwords](https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded) of my lwatchadmin, lwatchclient, and root users on MySQL. However, this didn't fix it.

Thank you for your help!!

**Comment by ofaaland** [comment]
@alvaromartin990 I believe that mysql/mariadb may not have been enabled (or were not detected) when you ran ./configure.

What OS and version are you building LMT on?
What arguments, if any, did you give when running ./configure ?
What output do you get from these commands?

```
# from within your build directory
grep -e MYSQL -e MARIA config.log
# on the system you build on, and also the system you have installed lmt on
rpm -qa | grep -i -e mariadb -e mysql | grep connect | sort
```

thanks!

**Comment by ofaaland** [comment]
Also, please provide the output of this command:
```
ls /usr/lib64/*/plugin/caching_sha2_password.so
```

**Comment by alvaromartin990** [comment]
Hi @ofaaland!

1. I am using _CentOS Linux release 7.9.2009 (Core)_. 
2. No arguments, just `./configure`. In addition, I am pretty sure MySQL was running and active when I rebuilt. I could potentially try rebuilding again if needed. 
3. I think this should be the right path and file: 
  ```
  sudo grep -e MYSQL -e MARIA /root/rpmbuild/BUILD/lmt-3.3.3/config.log
  ac_cv_path_MYSQL_CONFIG=/bin/mysql_config
  MYSQL_CFLAGS='-I/usr/include/mysql'
  MYSQL_CONFIG='/bin/mysql_config'
  MYSQL_FALSE='#'
  MYSQL_LIBS='-L/usr/lib64/mysql -lmysqlclient -lpthread -ldl  -lssl  -lcrypto -lresolv -lm -lrt'
  MYSQL_TRUE=''
  #define HAVE_MYSQL 1
  #define WITH_LSD_LIST_MYSQL_COMPAT 1
  
  ```
4. No output for: `rpm -qa | grep -i -e mariadb -e mysql | grep connect | sort`
5. No such file or directory
  ```
  ls /usr/lib64/*/plugin/caching_sha2_password.so
  ls: cannot access /usr/lib64/*/plugin/caching_sha2_password.so: No such file or directory
  ```
  
If helpful, I have installed mysql-community-devel-8.4.3-1.el7.x86_64.

Thank you for your help!

**Comment by ofaaland** [comment]
OK, that probably explains it
```
ls /usr/lib64/*/plugin/caching_sha2_password.so
ls: cannot access /usr/lib64/*/plugin/caching_sha2_password.so: No such file or directory
```
and
```
$ rpm -qa | grep -i -e mariadb -e mysql | grep connect | sort
$
```

For both mysql and mariadb, there are database-independent libraries that are used to connect to the running DB.  They abstract away details about finding the right socket to connect to, etc.   Using my test system as an example:

```
$ ls /usr/lib64/*/plugin/caching_sha2_password.so
/usr/lib64/mariadb/plugin/caching_sha2_password.so
$ rpm -qf /usr/lib64/*/plugin/caching_sha2_password.so
mariadb-connector-c-3.1.11-2.el8_3.x86_64
```

You need to install the mysql equivalent to this.  It's probably called `mysql-connector-c`.

**Comment by alvaromartin990** [comment]
Thank you for your message. I can't find a `mysql-connector-c-devel` compatible with my current SQL version:
```
sudo rpm -ivh mysql-connector-c-devel-6.1.11-1.el7.x86_64.rpm
warning: mysql-connector-c-devel-6.1.11-1.el7.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID 5072e1f5: NOKEY
error: Failed dependencies:
	MySQL-devel conflicts with mysql-connector-c-devel-6.1.11-1.el7.x86_64
	mysql-devel conflicts with mysql-connector-c-devel-6.1.11-1.el7.x86_64
	mysql-connector-c-devel < 6.2 is obsoleted by (installed) mysql-community-devel-8.4.3-1.el7.x86_64
```

Would you recommend switching to mariaDB?

**Comment by ofaaland** [comment]
Honestly, I'm not sure what's available for CentOS 7.9.  But mariadb has been out for a while, so it's worth a try.

**Comment by alvaromartin990** [comment]
Hello!

I gave it a try. I uninstalled MySQL and LMT. Found the necessary rpms for MariaDB, and rebuilt LMT. 

Took a little while, but... _/usr/sbin/lmtsh -f temp_ works now! Awesome!

While lustre is mounted on the client node, I found out through _ltop_ that my nodes are _inactive_ without me making any changes on these. I checked previous issues, however, re-mounting the entire file system did not help. Do you know if this could be an issue on my end, or could you please point me to any resources that might help troubleshoot this?

Thank you so much for your help!

**Comment by alvaromartin990** [comment]
Thank you for your answer, @ofaaland!

> It sounds like something about the "-connector-" packages should be in the instructions. Would you mind either proposing, or adding, something?

Sure, I will be happy to add it!

> When ltop shows MDTs and OSTs as inactive, are the clients doing i/o? And does ltop reflect that i/o (ie do the reported stats for MB/sec or opens/sec etc go up to reflect that i/o)?

Yes, the client is doing i/o, and I believe _ltop_ reflects it. I can see the inodes, bytes/s, MDops/s, and all of those stats before that white stripe (I will be a attaching a screenshot).

<img width="1002" alt="Screenshot 2024-10-31 at 8 38 58 PM" src="https://github.com/user-attachments/assets/e3d9833a-5457-407b-a239-073bd88cea3a">

> To test that you'll need to generate i/o for 60 seconds or more on the client(s), since lmt only samples periodically, and a too-short i/o test workload might not be reflected in multiple samples.

I ran mdtests for longer than 60 seconds, however, I did not observe any changes on the status of my metadata and ost nodes. Still inactive. Is there any other test you would recommend running to test that lmt is getting the data successfully? 

My management node is also acting as my client node. I am not sure if this might be an issue. 

> Ultimately, lmt gets status information, including inactive, from a procfile exported by Lustre. So if the clients are doing i/o successfully and ltop is reporting it, then we may need to move the question to Lustre mailing list, at http://lists.lustre.org/listinfo.cgi/lustre-discuss-lustre.org

Please, let me know if you think it is a better idea to move this over there.

Thank you!

**Comment by ofaaland** [comment]
Hi @alvaromartin990 The problem you are seeing is already documented in lmt issue #53 , and I provide background and explanation in a comment at https://github.com/LLNL/lmt/issues/53#issuecomment-2452275407 - we can discuss your "INACTIVE" issue further there.

Let's leave this issue open until you've made your documentation changes to let folks know the "connector" rpms are required.

**Comment by alvaromartin990** [comment]
Hi @ofaaland, 

> Hi @alvaromartin990 The problem you are seeing is already documented in lmt issue https://github.com/LLNL/lmt/issues/53 , and I provide background and explanation in a comment at https://github.com/LLNL/lmt/issues/53#issuecomment-2452275407 - we can discuss your "INACTIVE" issue further there.

Sounds good! Will discuss over there!

> Let's leave this issue open until you've made your documentation changes to let folks know the "connector" rpms are required.

I am not really sure how to push/open a pr to a wiki page. I tried pushing and got permission denied. Please, let me know how I can be helpful.

**Comment by ofaaland** [comment]
> I am not really sure how to push/open a pr to a wiki page. 

Hm, it looks like there isn't a way for you to do that.  Sorry, I didn't mean to ask for something impossible.  If you have already forked the repo, you could make a change to your fork and I could get your changes by copy-and-paste.  Or, you could submit a PR that adds a text file, which has your version of the markup in it, and I could get the text that way.  Thanks!

**Comment by alvaromartin990** [comment]
Hi @ofaaland,

Thank you for your response. Just forked it, added the modified Installation wiki file, and created a pull request!

Thank you for all your assistance. Best!

**Comment by ofaaland** [comment]
Updated the wiki at https://github.com/LLNL/lmt/wiki/Installation, closing this issue.
